# Basic run and window settings
runs: 100
window_start: 3
window_end: 5

# Undersampling settings
bal_train: true
bal_valid: false
bal_test: false

# Scaler settings (standard, robust, minmax)
scaler: 'robust'

# DataLoader settings
batch_size: 32
device: 'cpu'  # (cpu, cuda, mps)

# Model settings
model: 'ann' # (ann, ltc, cfc, lstm, gru)
hidden_size: 64
num_classes: 2

# Training settings
lr: 0.0001
epochs: 1000
patience: 100
threshold: 0.50

# Plot
window: 5 # (3, 4, 5)
